# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
jobs:
  main:
    docker:
      - image: node:16
    steps:
      - checkout
      - restore_cache:
          name: "Restore yarn cache if exists"
          keys:
            - yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run:
          name: "install"
          command: yarn install
      - save_cache:
          name: "Save yarn cache"
          paths:
            - node_modules
          key: yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run:
          name: "linting"
          command: yarn run lint
      - run:
          name: "build"
          command: yarn run build
      - run:
          name: "test"
          command: yarn run test
  staging:
    docker:
      - image: docker:20.10.12-git
    steps:
      - checkout
      - run:
          name: install make
          command: apk add make
      - run:
          name: Makefile test
          command: make -v

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  push: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      # - main
      - staging
